id: I4162481E
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3876final
source_file: null
initial_creation_type: input
imported: '2022-08-01T10:24:04.626780'
last_modified: '2022-08-01T10:24:04.626802'
parser: null
source_metadata:
  title: Commentary
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
